name: "Express Template"
run-name: "Express Template Workflow Ran By ${{ github.actor }}"

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Clean Dependencies
        run: npm ci

  format:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Clean Dependencies
        run: npm ci

      - name: "Fomat The Code with Prettier"
        run: npm run format

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Clean Dependencies
        run: npm ci

      - name: "Lint The Code with ESlint"
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Clean Dependencies
        run: npm ci

      - name: "Test The Code With Vitest"
        run: npm run test:run
