const INTERNAL_SERVER_STATUS_CODE = 500;
const NO_CONTENT_STATUS_CODE = 204;
const OK_STATUS_CODE = 200;

enum HttpStatusCode {
	INTERNAL_SERVER_ERROR = INTERNAL_SERVER_STATUS_CODE,
	NO_CONTENT = NO_CONTENT_STATUS_CODE,
	OK = OK_STATUS_CODE,
}

export { HttpStatusCode };
