const INTERNAL_SERVER_STATUS_CODE = 500;
const NO_CONTENT_STATUS_CODE = 204;
const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const NOT_FOUND_STATUS_CODE = 404;
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_STATUS_CODE = 401;
const FORBIDDEN_STATUS_CODE = 403;

enum HttpStatusCode {
	INTERNAL_SERVER_ERROR = INTERNAL_SERVER_STATUS_CODE,
	NO_CONTENT = NO_CONTENT_STATUS_CODE,
	OK = OK_STATUS_CODE,
	CREATED = CREATED_STATUS_CODE,
	NOT_FOUND = NOT_FOUND_STATUS_CODE,
	BAD_REQUEST = BAD_REQUEST_STATUS_CODE,
	UNAUTHORIZED = UNAUTHORIZED_STATUS_CODE,
	FORBIDDEN = FORBIDDEN_STATUS_CODE,
}

export { HttpStatusCode };
